---
http_interactions:
- request:
    method: delete
    uri: https://circleci.com/api/v1/project/mtchavez/circleci/enable?circle-token=<TOKEN>
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - Ruby
      Host:
      - circleci.com
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Fri, 29 Jul 2016 00:23:24 GMT
      Server:
      - nginx
      Set-Cookie:
      - ab_test_user_seed=0.3396850799247606;Expires=Sat, 29 Jul 2017 00:23:24 +0000;Path=/;Secure
      - ring-session=qDnvmc7ZnQAUXGsGcJ%2FoRaxOYLDZhNkK2js6tW2Hqdw%2FuE2Q%2FQfUhUWZkorG2ELeuNdXgmuO%2F%2FZfv3zmurXOKggKuHFdomDLZJvnbTPJYW5AxwNMEmuCTgSJvsX3EsqfBlgQuXIQYwHW2d8yOTOY2dINGK8UPyBbm5uHUqiH526rkItWPWMxOTxLzQgd3%2BWkHXIA3%2FQi93UX7Db9BA3lRMgGyY4CKl6uuaFTzJ7sCCI%3D--10R8aQe3VOgcDVN5ohjZ3ttziG%2BD3hUiklTIYvw9NPY%3D;Path=/;HttpOnly;Expires=Sat,
        29 Jul 2017 00:19:56 +0000;Max-Age=31536000;Secure
      Strict-Transport-Security:
      - max-age=15724800
      X-Circleci-Identity:
      - i-ffc60260
      X-Circleci-Request-Id:
      - 4595a521-5309-4cdc-8d7c-982ae84b954d
      X-Circleci-Scopes:
      - ":all"
      - ":none"
      - ":read-settings"
      - ":status"
      - ":trigger-builds"
      - ":view-builds"
      - ":write-settings"
      X-Frame-Options:
      - DENY
      X-Route:
      - "/enable"
      Content-Length:
      - '1370'
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: '{"irc_server":null,"scopes":["write-settings","view-builds","read-settings","trigger-builds","all","status","none"],"irc_keyword":null,"followed":false,"vcs-type":"github","aws":{"keypair":null},"slack_webhook_url":null,"flowdock_api_token":null,"parallel":1,"username":"mtchavez","campfire_room":null,"extra":"","branches":{"master":{"running_builds":[],"recent_builds":[{"build_num":230,"status":"failed","outcome":"failed","added-at":"2016-07-29T00:17:53.302Z"},{"build_num":232,"status":"failed","outcome":"failed","added-at":"2016-07-29T00:18:13.703Z"},{"build_num":228,"status":"failed","outcome":"failed","added-at":"2016-07-29T00:17:51.151Z"},{"build_num":229,"status":"failed","outcome":"failed","added-at":"2016-07-29T00:18:01.106Z"},{"build_num":231,"status":"failed","outcome":"failed","added-at":"2016-07-29T00:17:52.096Z"}],"pusher_logins":["mtchavez"]},"min-ruby-ver":{"running_builds":[],"recent_builds":[{"build_num":220,"status":"success","outcome":"success","added-at":"2016-07-28T03:57:42.973Z"},{"build_num":219,"status":"success","outcome":"success","added-at":"2016-07-28T03:58:37.895Z"}],"pusher_logins":["mtchavez"]},"pull%2F46":{"running_builds":[],"recent_builds":[{"build_num":91,"status":"success","outcome":"success","added-at":"2016-01-17T20:51:00.048Z"}],"pusher_logins":[]},"pull%2F66":{"running_builds":[],"recent_builds":[{"build_num":134,"status":"failed","outcome":"failed","added-at":"2016-03-14T16:57:59.459Z"}],"pusher_logins":[]},"pull%2F69":{"running_builds":[],"recent_builds":[{"build_num":139,"status":"success","outcome":"success","added-at":"2016-04-25T20:50:46.002Z"}],"pusher_logins":[]},"typo":{"running_builds":[],"recent_builds":[{"build_num":227,"status":"success","outcome":"success","added-at":"2016-07-29T00:13:47.745Z"},{"build_num":226,"status":"success","outcome":"success","added-at":"2016-07-29T00:10:45.273Z"},{"build_num":225,"status":"success","outcome":"success","added-at":"2016-07-29T00:09:01.773Z"}],"pusher_logins":["mtchavez"]}},"slack_subdomain":null,"setup":"","campfire_subdomain":null,"slack_notify_prefs":null,"irc_password":null,"vcs_url":"https://github.com/mtchavez/circleci","default_branch":"master","hipchat_api_token":null,"irc_username":null,"language":"Ruby","slack_channel_override":null,"hipchat_notify":null,"slack_api_token":null,"has_usable_key":false,"irc_notify_prefs":null,"campfire_token":null,"slack_channel":null,"feature_flags":{"trusty-beta":false,"osx":false,"set-github-status":true,"build-prs-only":false,"fleet":null,"build-fork-prs":false,"autocancel-builds":false,"junit":true,"oss":true},"campfire_notify_prefs":null,"hipchat_room":null,"post_dependencies":"","heroku_deploy_user":null,"irc_channel":null,"oss":true,"reponame":"circleci","hipchat_notify_prefs":null,"compile":"","dependencies":"","test":"bundle
        exec rake rubocop && bundle exec rspec -r rspec_junit_formatter --format RspecJunitFormatter
        -o $CIRCLE_TEST_REPORTS/rspec/junit.xml","ssh_keys":[{"hostname":"hostname","public_key":"ssh-rsa
        AAAAB3NzaC1yc2EAAAADAQABAAABAQDDC7Ca3FXm9nAC5kpIQ+uB2a7ShJkj4PvjNJSsI1rmz2Z8eXDMLOEW08qGXBjFWlDtZkGtAw2U8UmaHKPcJ3YM+Ss5sw0sRURW3pPpqF0JzKvDaNg8UxDLBk8CFxb2YLjjSpM2G5BMY5w38Af/U/8Hhb284lg7sdbtM9rRLlDeYVEx+T/nVOWsH+j3SAICZfpKb7GCz1OCbH2lhEXQqPMin+0UYw4ePrB0NvtC/x55fQ+cK1K3jbyVkZIXRw1KZAhUjEGCLu3CYsqkWCpLUsAABv36Vdb7KH9/kWXhUGKsS8LeiVLrJQDFaENDbvBo4rum1ORhgbD72DtBZKON4r6/","fingerprint":"83:3d:57:76:98:96:f6:ae:20:57:18:84:a6:4d:58:9d"},{"hostname":"hostname","public_key":"ssh-rsa
        AAAAB3NzaC1yc2EAAAADAQABAAABAQDDC7Ca3FXm9nAC5kpIQ+uB2a7ShJkj4PvjNJSsI1rmz2Z8eXDMLOEW08qGXBjFWlDtZkGtAw2U8UmaHKPcJ3YM+Ss5sw0sRURW3pPpqF0JzKvDaNg8UxDLBk8CFxb2YLjjSpM2G5BMY5w38Af/U/8Hhb284lg7sdbtM9rRLlDeYVEx+T/nVOWsH+j3SAICZfpKb7GCz1OCbH2lhEXQqPMin+0UYw4ePrB0NvtC/x55fQ+cK1K3jbyVkZIXRw1KZAhUjEGCLu3CYsqkWCpLUsAABv36Vdb7KH9/kWXhUGKsS8LeiVLrJQDFaENDbvBo4rum1ORhgbD72DtBZKON4r6/","fingerprint":"83:3d:57:76:98:96:f6:ae:20:57:18:84:a6:4d:58:9d"},{"hostname":"hostname","public_key":"ssh-rsa
        AAAAB3NzaC1yc2EAAAADAQABAAABAQDDC7Ca3FXm9nAC5kpIQ+uB2a7ShJkj4PvjNJSsI1rmz2Z8eXDMLOEW08qGXBjFWlDtZkGtAw2U8UmaHKPcJ3YM+Ss5sw0sRURW3pPpqF0JzKvDaNg8UxDLBk8CFxb2YLjjSpM2G5BMY5w38Af/U/8Hhb284lg7sdbtM9rRLlDeYVEx+T/nVOWsH+j3SAICZfpKb7GCz1OCbH2lhEXQqPMin+0UYw4ePrB0NvtC/x55fQ+cK1K3jbyVkZIXRw1KZAhUjEGCLu3CYsqkWCpLUsAABv36Vdb7KH9/kWXhUGKsS8LeiVLrJQDFaENDbvBo4rum1ORhgbD72DtBZKON4r6/","fingerprint":"83:3d:57:76:98:96:f6:ae:20:57:18:84:a6:4d:58:9d"},{"hostname":"hostname","public_key":"ssh-rsa
        AAAAB3NzaC1yc2EAAAADAQABAAABAQDDC7Ca3FXm9nAC5kpIQ+uB2a7ShJkj4PvjNJSsI1rmz2Z8eXDMLOEW08qGXBjFWlDtZkGtAw2U8UmaHKPcJ3YM+Ss5sw0sRURW3pPpqF0JzKvDaNg8UxDLBk8CFxb2YLjjSpM2G5BMY5w38Af/U/8Hhb284lg7sdbtM9rRLlDeYVEx+T/nVOWsH+j3SAICZfpKb7GCz1OCbH2lhEXQqPMin+0UYw4ePrB0NvtC/x55fQ+cK1K3jbyVkZIXRw1KZAhUjEGCLu3CYsqkWCpLUsAABv36Vdb7KH9/kWXhUGKsS8LeiVLrJQDFaENDbvBo4rum1ORhgbD72DtBZKON4r6/","fingerprint":"83:3d:57:76:98:96:f6:ae:20:57:18:84:a6:4d:58:9d"}]}'
    http_version: 
  recorded_at: Fri, 29 Jul 2016 00:23:38 GMT
recorded_with: VCR 3.0.3
