---
http_interactions:
- request:
    method: get
    uri: https://circleci.com/api/v1.1/project/github/mtchavez/dotfiles/checkout-key?circle-token=<TOKEN>
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - Ruby
      Host:
      - circleci.com
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Access-Control-Allow-Origin:
      - "*"
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Tue, 20 Dec 2016 23:56:06 GMT
      Server:
      - nginx
      Set-Cookie:
      - ring-session=jq2GKql1nY7ZC7Khp3uPxeg2H%2Bil6BpxlmvVb7pdqVVCQgBx%2FvHVfvLKXgYQipeV1Z51Z0%2Fmd9d%2BugFu31yG7XhmnfdUtEzKG7lO9QSXzqQmg7kWgy67yCPwbnTm9GD8C1o63uDWTvV0bhe5VcE2iDcpqoQ6ajO%2FZ3ycJjC8a%2BnW%2FVi5WbXS69nwqkkM5IYqS6%2FGQcgVw%2Fqb%2BSfcJUckEJUqf2mJ%2BHnrJTfTFx08xxE%3D--dtEIxcyQ16QOtfAbH5DW%2BSQAiEYCTMqEkls0IYy03Eo%3D;Path=/;HttpOnly;Expires=Wed,
        20 Dec 2017 23:03:36 +0000;Max-Age=31536000;Secure
      X-Circleci-Identity:
      - i-b4bbd927
      X-Circleci-Request-Id:
      - 8b35fa62-507b-4fa1-8fd7-7afd467bba32
      X-Frame-Options:
      - DENY
      X-Route:
      - "/checkout-key"
      Content-Length:
      - '31'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"message":"Project not found"}'
    http_version: 
  recorded_at: Tue, 20 Dec 2016 23:54:30 GMT
recorded_with: VCR 3.0.3
