---
http_interactions:
- request:
    method: post
    uri: https://circleci.com/api/v1/project/mtchavez/circleci/enable?circle-token=<TOKEN>
    body:
      encoding: ASCII-8BIT
      string: ''
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      Content-Length:
      - '0'
      Content-Type:
      - application/x-www-form-urlencoded
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      Content-Type:
      - text/plain; charset=utf-8
      Date:
      - Mon, 25 Jul 2016 23:52:01 GMT
      Server:
      - nginx
      Set-Cookie:
      - ab_test_user_seed=0.3396850799247606;Expires=Tue, 25 Jul 2017 23:52:00 +0000;Path=/;Secure
      - ring-session=od8uWS1QA%2FlVVDUd6W%2FLKqeCIj3s9hctRr4Vn3yPYzQX4A7zoiRdfq1kzQ0Phnq80jnb8dwq74ns51ZfKSuB2ag3arxiPdsLYvLDS7a%2BG5YCtrD6FqYAVuWTX0WCB%2Bnk9mmX6AAvapu70%2BeEbVfOoXbhS8RadtThJJvHt8RFZL4a61ywhrtWRZOj0ZQgg6HqQLgqmrVzkHjHd0hXHgiN%2B5WqOF7I%2B3E%2B5oGNVJ6FAtU%3D--moN2ym1hEQ1iO%2FpgQjfYZH314om9SGyTXJcDBQcB8V8%3D;Path=/;HttpOnly;Expires=Tue,
        25 Jul 2017 21:35:57 +0000;Max-Age=31536000;Secure
      Strict-Transport-Security:
      - max-age=15724800
      X-Circleci-Identity:
      - i-d7ce0a48
      X-Circleci-Request-Id:
      - 13263570-ee11-49c6-8435-314ed9e39d25
      X-Circleci-Scopes:
      - ":all"
      - ":none"
      - ":read-settings"
      - ":status"
      - ":trigger-builds"
      - ":view-builds"
      - ":write-settings"
      X-Frame-Options:
      - DENY
      X-Route:
      - "/enable"
      Content-Length:
      - '1437'
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAOxXWXOjOBB+n19BUbvzkmBzg3nzlcvOZcc5vDVFCRAGGyMi
        CR+Zyn9fAbFjEnvLNbPOy24qlUB/kvj0dbfU/fMbx/Ehdm0C8QxinrO4OI2i
        48xMXJRAkpn+4vg5DikUCKQ0jEeEP+b4WQjngpOGkZe/Ygi8Ek5xOBpBvDEE
        RFH2j1BA09wQoxjy3I/jFYkJXM4R9kosfBRFaA5zI8UpzI0zlwh0mcDMyI9C
        GqQOnwNgnhP+yZ7ZG1svAeF6V8z4WuwsAu7EnkMnQGhipzgqf5F9z0NsAEhC
        m6IJjEtwAjDbCMznSLklZeLFYFqwmVI3ADP4UvBxwTTxQwxtjNC0tAxcUAzy
        GcVIB4PYDeAmfQ/OBA8mMPZg7IabEANxGsdMavtN3txLuZIFCl0Y0xK4mpl9
        KzPbcZozklTl+B16c07Gi6SuCwnhN1CUUhe9bXQLDDwPegKgOS6Lki6IhiBr
        d5JhybKlyhVTNob82/jXDbpJSgKI7QiNwngVcWshuR/5sNdiND8FhBaRegAt
        arVDa5EJIVqaVBE1+V2L43+gZH4BJaXGPFRRVHE/SsbXUFIMppKyHyXtKyiZ
        lmxUVEPfj5L+RZTUiqyqv51XCTuZ/pRPVP0wqVWTDqiGJEjGnZyllSWKFVE1
        91VjqwT6gSSQFHW7Bj4II3bD7ZDgM7pFAUWQ1DtJtzTD0moVVav9ngK1Qylw
        yPNVzXOCRYFoqXpFFOVf04AVFuhQ18uOAPi3D05RqmjynqfUwW//jJJmiXKl
        phv7URK/gJKsZEeFIpp7UTK/oi5gv5pe0SVtP0pfcb3IkqWpFaWm/Pr18qHq
        JqnjoSkIy0U1axzSZKMaXtfNO4bnS8WIhv7STjD0SQnOeokEEPKpmWB9w6rc
        5wNKE2JVq0X7UGECVVfcqy5bIYJuWJDxoA/SiKV4XqIXVX5RhOZwECZsGt3R
        LmRcNhuENRCBeJSCUeGVXuos+Y2tsQXjGEY2Yk0ZDr3yzNUHi/1vEWY7kwCw
        zRPgRDBrtEr9VEZyp5prX3xeskS23ERBFpBsjh+B0WZPwz5J6FJwIM2bHx9E
        BL6du4gsPppYWAiFf4T3CF+xXmWEkGAioDhafpztRxDSTVbrGT7Ck2zaxxkg
        pchlToaR8H6ebw4Yp3FIP5BAZE1rHetrzXaqunLip8YwQYTaH9u+t7Rg2YYm
        aYZGaJmH1adY2+aMDYb5O4YJWjes5Vgvx9a2aEDThNUjG6R2cKWQFCeKk8Ze
        BDm4gC6HwQRyOHWQixLu+3euhJGE/RVw8WDnUtvMU1NAWa5xglA8c70MvsjQ
        k3cQcX80z3vNbtu+a/fv7F775rp316/mS1XzpSqLafSWYiTIMqB0WfMBk32t
        yfplXRY5Ueiu0iZbQMAEcHX201CuXkBTWrpyO3tt1W/rjcxcv221mkYTKCeP
        01pcb2qT5Pz2KG3IwOgHF5OxejMbX130ybmEpy/y0ISPrcvudftBNJ9PHxvj
        k4eoRYeTU1qfywNzMAVnnRv3Qnm6POoTjcxF0hv0HpTkJnk+ES9eOrMWuBqZ
        g0Wr25iYzZOFIz91x+N+cimfao3LJ22umHW/OqiaZ4Ejm2o0Mojn0Msa7nWj
        Fny6by+O7qrx/fUDOTsaK/36eXPoJx3HOG2+SNdN50yOgvbj7fPNZRgfiYOn
        uQpvcEO8mtFmdaFp/u2R25E6ythZ3k+G54+9udQZ1oPBuH3a7KZK84k8Tx6a
        SXdAmDAzRb/3HKNzVqtOHh6DwWmH9M0uDO+7+OK2dQLaVy1n1kAqTqfSdS8Y
        OS1DbtHGsHN9pWK9unKJzyoyiBMcxkWUmYqleFn5a+hWzbRquuXrFoBWVg8a
        lmRapmoB3VLZGIZ6/LeN2/V/5/8Hnc/qk9e/AQAA//8DACPPZQD/FAAA
    http_version: 
  recorded_at: Mon, 25 Jul 2016 23:52:05 GMT
recorded_with: VCR 3.0.3
